AWSTemplateFormatVersion: 2010-09-09

Description: |
 Creation of ec2 instance with elastic ip 
 Either it is created or not can be decided

Parameters:
  EnvironmentName:
    Type: String
    Default: do
    AllowedValues:
     - do
     - don't

Conditions:
  createEip: !Equals [!Ref EnvironmentName, do]

Resources:

  firstec2instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-051f8a213df8bc089
      InstanceType: t2.micro
      KeyName: public-key-1
      SecurityGroups:
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'ssh securitygroup'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ElasticIp:
    Type: 'AWS::EC2::EIP'
    Condition: createEip
    Properties:
      InstanceId: !Ref firstec2instance

Outputs:
  Instance:
    Description: 'InstanceId'
    Value: !Ref firstec2instance
    
  ip:
    Description: 'Ip address'
    Value: !GetAtt firstec2instance.PublicIp 