AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template will deploys ec2 instance with parameters
Parameters:

  instanceType: 
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.nano

  KeyName:
    Type: 'AWS::EC2::KeyPair::KeyName'

Resources:

firstec2instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-051f8a213df8bc089
      InstanceType: !Ref instanceType
      KeyName: !Ref ec2Key
      SecurityGroups:
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ssh securitygroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ec2Key:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: new-keypair-01  