AWSTemplateFormatVersion: 2010-09-09
Description: |
 Creation of ec2 instance(along with security group and keypair) with mappings to different regions with choice to choose the instance type.
 In Output Instanceid and ip address is displayed.

Mappings:
  Regionmap:
    us-east-1:
      ami: ami-051f8a213df8bc089
    us-east-2:
      ami: ami-0900fe555666598a2  

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.nano
      - t2.small
      - t2.large

Resources:
  
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - Regionmap
        - !Ref 'AWS::Region'
        - ami

      InstanceType: !Ref InstanceType
      KeyName: !Ref createkeypair 
      SecurityGroupIds:
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'ssh securitygroup'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0   

  createkeypair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: key-create-1
              
Outputs:
  Instance:
    Description: 'InstanceId'
    Value: !Ref Ec2Instance
    
  ip:
    Description: 'Ip address'
    Value: !GetAtt Ec2Instance.PublicIp   

  Instancetype:
    Description: 'instance type'
    Value: !GetAtt Ec2Instance.InstanceType  