AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template will just deploys ec2 instance
Resources:

  firstec2instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-051f8a213df8bc089
      InstanceType: t2.micro
      KeyName: !Ref ec2Key
      SecurityGroups:
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ssh securitygroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  ec2Key:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: new-keypair-01