AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template will just deploys ec2 instance

Resources:

  SeciondEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-051f8a213df8bc089
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: Second aws machine