AWSTemplateFormatVersion: 2010-09-09

Description: |
  Creating Ec2 instance with conditions on instance type
  
Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues:
     - dev
     - prod
     - qa
    
Mappings:
  SelectInstance:
    dev:
      Ec2ins: t2.micro
    prod:
      Ec2ins: t2.small
    qa:
      Ec2ins: t2.nano     

Conditions:
  createfirst: !Equals [!Ref EnvironmentName, dev]
  createsecond: !Equals [!Ref EnvironmentName, prod]
  createthird: !Equals [!Ref EnvironmentName, qa]

Resources:
  Ec2Instance1:
    Type: AWS::EC2::Instance
    Condition: createfirst
    Properties:
      ImageId: ami-051f8a213df8bc089    
      InstanceType: !FindInMap
        - SelectInstance
        - !Ref EnvironmentName
        - Ec2ins
      KeyName: test-01 
      SecurityGroups:
        - !Ref SSHSecurityGroup

  Ec2Instance2:
    Type: AWS::EC2::Instance
    Condition: createsecond
    Properties:
      ImageId: ami-051f8a213df8bc089
      InstanceType: !FindInMap
        - SelectInstance
        - !Ref EnvironmentName
        - Ec2ins
      KeyName: test-01 
      SecurityGroups:
        - !Ref SSHSecurityGroup      

  Ec2Instance3:
    Type: AWS::EC2::Instance
    Condition: createthird
    Properties:
      ImageId: ami-051f8a213df8bc089
      InstanceType: !FindInMap
        - SelectInstance
        - !Ref EnvironmentName
        - Ec2ins
      KeyName: test-01 
      SecurityGroups:
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'ssh securitygroup'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0