AWSTemplateFormatVersion: 2010-09-09

Description: |
  Creating security group with conditions.
  
Parameters:
  EnvironmentName:
    Type: String
    Default: public
    AllowedValues:
     - public
     - private

Conditions:
  createpublic: !Equals [!Ref EnvironmentName, public]
  createprivate: !Equals [!Ref EnvironmentName, private] 

Resources:
         
  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup 
    Condition: createpublic 
    Properties:
      GroupDescription: 'public ssh securitygroup' 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  
      Tags:
        - Key: Name
          Value: public SSH 1

  firstec2instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-051f8a213df8bc089
      InstanceType: t2.micro
      SecurityGroupIds:
        - !If [createpublic, !Ref EnvironmentName , !Ref AWS::NoValue]